# Generated by Django 2.1.3 on 2018-11-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20181120_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.IntegerField(default=0, verbose_name='親'),
        ),
    ]
