# Generated by Django 2.1.3 on 2018-11-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='親'),
        ),
    ]
